### ISSUE TITLE
Logo Proposal for Threads

### ISSUE THREAD

**Issue by area55git** [eschirtz/Threads#4]
Hi @eschirtz, In response to your Logo request and analyzing your project "THREADS", this is the idea I have for the logo design.

[![LOGO_PROPOSAL_FOR_THREADS.jpg](https://s33.postimg.cc/69n4gba7j/LOGO_PROPOSAL_FOR_THREADS.jpg)](https://postimg.cc/image/ef56egygb/)

Remember that this is a sketch, you can suggest any change.

I hope you like it!

**Comment by eschirtz** [comment]
Wow! That's excellent man. I'll show it to some other people for review and comments. 

Nice work

**Comment by eschirtz** [comment]
Hey @area55git 

I showed it to a couple people, most people like the blue version, since it seems a little more inviting and playful. Of course it works well mono-chrome too which is perfect. But for an app icon, it would be nice to get a color version like you have. 

Could you try out some of the colors from the color pallet i'm using? Just see what you can come up with maybe using the 'primary' green, and maybe the 'error' red? 

    primary: '#789f89',
    secondary: '#0a373a', //
    accent: '#e3d9a2', //
    error: '#e0694e', //
    info: '#048384', //
    success: '#5f7200', //
    warning: '#deb853' //

Great stuff, please let me know how you would like to be credited on the site, i'll be sure to make it happen

Otherwise, just cleaning up the paths ( I know this version is just a sketch ), then I think we have something really great

**Comment by area55git** [comment]
Great, I'll work on the other colors, with the logo in the readme folder and a recommendation as collaboration is enough for me, of course, if you use it on your website it's perfect!

**Comment by area55git** [comment]
Hi @eschirtz These are the sketches with the suggested color palette

[![LOGO_PROPOSAL_FOR_THREADS.jpg](https://s33.postimg.cc/p37jr490v/LOGO_PROPOSAL_FOR_THREADS.jpg)](https://postimg.cc/image/70egzwd63/)

**Comment by eschirtz** [comment]
These are great. 

I really like the red scheme, the last row of your image. The logo on white, looks great with all the colors. I think that the logo on red looks a little too busy with the blue and the yellow parts, so we may just want to go with all white logo when on red. (like you have on the top row with the grey background).

I think i'm going to re-theme my application to match the logo that you have created (change primary color to that red, and make the whole thing lighter). Let's move ahead with this logo, what's the next step? Just sending over the EPS/AI files? 

Great work on this.

P.S. could you send me your professional contact information? I own a video production company and we often have clients that need logos, I'd love to pass on some paid work to you. 

Best,

**Comment by eschirtz** [comment]
After thought,

We could try changing the blue "T", on when on red to another color that's subtle like that yellow you have. That may work instead of just turning the whole thing white.

**Comment by eschirtz** [comment]
![logo-proposal-2-annotated](https://user-images.githubusercontent.com/24927782/43281525-8725f5f4-90d9-11e8-9486-8bc950492eca.jpg)

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_THREADS_2.jpg](https://s33.postimg.cc/60xv2otdr/LOGO_PROPOSAL_FOR_THREADS_2.jpg)](https://postimg.cc/image/9kjsshw3f/)

**Comment by area55git** [comment]
@eschirtz When you need a private job, you can contact me by email
Here you can see some of my work: www.instagram.com/area55_ib

I would really be very grateful to work with you. Thank you very much!

**Comment by eschirtz** [comment]
This is great! Could I see what it would look like to have the yellow on both of the two crossed "T's", basically taking what you have on the second from the left design, and putting it over the red background? 

Other than that, I love it, I think the first image and last image in this draft is what we'll go with, unless the yellow version comes out looking good too, then we'll use all three!

I'll follow up with a photo to try and explain more clearly

**Comment by eschirtz** [comment]
![logo-proposal-3-annotated](https://user-images.githubusercontent.com/24927782/43295061-2d6f0d1e-9108-11e8-993c-d2f1d0e02705.jpg)

**Comment by area55git** [comment]
I love this selection of colors, those could be the definitive ones

[![LOGO_PROPOSAL_FOR_THREADS_2.jpg](https://s33.postimg.cc/b0hzougyn/LOGO_PROPOSAL_FOR_THREADS_2.jpg)](https://postimg.cc/image/61uhabd5n/)

**Comment by eschirtz** [comment]
I agree! 

These designs are final!

**Comment by area55git** [comment]
Perfect, I will prepare the designs and send them in various formats and sizes (SVG, PNG, EPS, etc.)
I would like to make a PR and place the logo # 1 in the Readme folder to merge.
I think I can finish it in about 4 hours.

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_THREADS_3.jpg](https://s33.postimg.cc/dngc7xvfz/LOGO_PROPOSAL_FOR_THREADS_3.jpg)](https://postimg.cc/image/9ebm5rs6j/)

Which do you like?

**Comment by eschirtz** [comment]
Awesome, you have the go-ahead!

**Comment by eschirtz** [comment]
I agree, I think logo #1 would work really well, that or logo #4

**Comment by area55git** [comment]
You can open it with # 4 and in the end close the Readme folder with # 1, it would look great.

**Comment by area55git** [comment]
Example:

[![LOGO_PROPOSAL_FOR_THREADS_3.jpg](https://s33.postimg.cc/ylmi63fvz/LOGO_PROPOSAL_FOR_THREADS_3.jpg)](https://postimg.cc/image/446nejsiz/)

**Comment by eschirtz** [comment]
That looks really slick, I like it

**Comment by eschirtz** [comment]
Please add a section that credits you, and provides any links to where to find your work. You have done a great job at this and you deserve to receive credit

**Comment by eschirtz** [comment]
Hey,

Just wanted to make sure I didn't miss anything from you. If you got busy no worries, just checking in!

**Comment by area55git** [comment]
Hi @eschirtz In this link are all the files

### [FILE DOWNLOAD](https://drive.google.com/open?id=1YbhBy7mmfDue9OnvnDcMebtzj2Xb59oA)

[![derechos.jpg](https://s33.postimg.cc/5mr0mv98v/derechos.jpg)](https://postimg.cc/image/i1dsn70qz/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
PR #5

**Comment by area55git** [comment]
I do not know much about GitHub, can you create the Logo folder? to be able to upload the files

**Comment by eschirtz** [comment]
Yeah, 

I'm rather new to GitHub collaboration as well, but I'll try to get a folder uploaded for you!

Also, impressive delivery package, you are very professional. Let's stay in touch, I may have paid work for you in the future!

**Comment by eschirtz** [comment]
If it's ok with you, I may just keep the logo files locally in order to keep the project size down. Then load in just the graphics I need on the site. 

I'll use the rest of the variations for advertising and whatnot once I reach that stage.

Also, I'm going to add a section about you on the "Info" page. Do you have a website or bio I could use to credit you more?

**Comment by area55git** [comment]
Only my GitHub @area55git account and my Instagram account www.instagram.com/area55_ib

**Comment by area55git** [comment]
Discord: area-55#7708

**Comment by area55git** [comment]
I love your website!
